name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install poetry
        uses: snok/install-poetry@v1
+       with:
+         version: 1.8.2
+         virtualenvs-create: true
+         virtualenvs-in-project: true

      - name: Install package
        run: poetry install

+     - name: List installed packages
+       run: poetry show

      - name: Test with pytest
-       run: poetry run pytest
+       run: poetry run pytest tests/ -v

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml # coverage report
+         fail_ci_if_error: true
+         verbose: true

      - name: Build documentation
        run: poetry run make html --directory docs/
